- name: Mettre à jour tous les nœuds PVE
  hosts: pve
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      apt:
        upgrade: dist
